name: Java CI with Gradle

on:
  push:
    branches: [ "ReBuildMaster" ]
  pull_request:
    branches: [ "ReBuildMaster" ]


env:
  NAME: Key1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      JAVA_VERSION: '21'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'
        

      - name: Set executable permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Print Key1
        run: echo "My Link key is ${{secrets.SUP3R_5EC73T_KE1}}"
        env: 
          BUILD: "is it running?"
          SUP3R_5EC73T_KE1: ${{secrets.SUP3R_5EC73T_KE1}}
      
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set executable permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
